id: I8C8254B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T02:51:27+00:00'
last_modified: '2022-06-07T21:50:51.196497+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB16423
  title: མཆོག་སྤྲུལ་འཇམ་དབྱངས་ཆོས་འཕེལ་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5D9C:
      image_group_id: I1PD33765
      title: ''
      total_pages: 90
      order: 1
      base_file: 5D9C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
