id: P004305
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:09:13.183411
source_metadata:
  id: bdr:W2DB16423
  title: མཆོག་སྤྲུལ་འཇམ་དབྱངས་ཆོས་འཕེལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    e8afffb9985f469abdbeee1481aacc81:
      image_group_id: I1PD33765
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
