id: P004305
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB16423
  title: མཆོག་སྤྲུལ་འཇམ་དབྱངས་ཆོས་འཕེལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    e8afffb9985f469abdbeee1481aacc81:
      image_group_id: I1PD33765
      title: ''
      volume_number: 1
      total_pages: 90
      base_file: v001.txt
